package az.code.turboplus.services;

import az.code.turboplus.dtos.ListingListDTO;
import az.code.turboplus.dtos.SearchRequest;
import az.code.turboplus.enums.*;
import az.code.turboplus.models.*;
import az.code.turboplus.repositories.*;
import com.github.javafaker.Faker;
import org.aspectj.lang.annotation.Before;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;

@ExtendWith(SpringExtension.class)
@SpringBootTest
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
class ListingServiceImplTest {
    @Autowired
    ListingService listService;
    @Autowired
    UserRepository userRepo;
    @Autowired
    CityRepository cityRepo;
    @Autowired
    MakeRepository makeRepo;
    @Autowired
    ModelRepository modelRepo;
    @Autowired
    ListingRepository listRepo;

    @Test
    void search() {
        String make = "BMW";
        List<ListingListDTO> listings = listService.search(SearchRequest.builder()
                .make(make)
                .build(), 100, 0);
        Assertions.assertEquals(7, listings.size());
    }

    @BeforeEach
    public void init() {
        Faker faker = new Faker();
        Random random = new Random();
        List<User> users = new ArrayList<>();
        users.add((User.builder().username("tonette.mclaughlin").email("tracey.schiller@yahoo.com").phoneNumber("+994709587412").name("Suzanna Kling").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("daren.sipes").email("duane.pfeffer@hotmail.com").phoneNumber("+994709587412").name("Hung Kub MD").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("kendrick.wunsch").email("mayra.nitzsche@gmail.com").phoneNumber("+994709587412").name("Justin Swift PhD").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("lottie.fritsch").email("odell.mayer@gmail.com").phoneNumber("+994709587412").name("Annemarie Smith").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("marcelino.skiles").email("melda.oreilly@yahoo.com").phoneNumber("+994709587412").name("Senaida Waters").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("guadalupe.kuhlman").email("samantha.rau@yahoo.com").phoneNumber("+994709587412").name("Ian Franecki").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("nikole.hermiston").email("annette.gottlieb@hotmail.com").phoneNumber("+994709587412").name("Elizbeth Thiel").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("zane.bins").email("bruce.marks@gmail.com").phoneNumber("+994709587412").name("James Barrows III").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("lula.murray").email("april.altenwerth@yahoo.com").phoneNumber("+994709587412").name("Miss Noble Schroeder").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        users.add((User.builder().username("abraham.fahey").email("freeman.thiel@gmail.com").phoneNumber("+994709587412").name("Miss Lavonda Batz").balance(9999.9).freeListing(true).registerTime(LocalDateTime.now()).build()));
        userRepo.saveAll(users);
        List<City> cities = new ArrayList<>();
        cities.add(City.builder().name("Port Deonmouth").build());
        cities.add(City.builder().name("Zemlakville").build());
        cities.add(City.builder().name("Wardchester").build());
        cities.add(City.builder().name("Omarton").build());
        cities.add(City.builder().name("Mohammedside").build());
        cities.add(City.builder().name("Lake Clemmiestad").build());
        cities.add(City.builder().name("Port Krista").build());
        cities.add(City.builder().name("Daughertybury").build());
        cities.add(City.builder().name("Aufderharland").build());
        cities.add(City.builder().name("West Moniquehaven").build());
        cityRepo.saveAll(cities);

        List<Make> makes = new ArrayList<>();
        List<Model> models = new LinkedList<>();
        makes.add(Make.builder().name("BMW").build());
        models.add(Model.builder().name("Moen Group").build());
        models.add(Model.builder().name("Spinka-Hane").build());
        models.add(Model.builder().name("Towne-Hermann").build());
        models.add(Model.builder().name("Treutel and Sons").build());
        models.add(Model.builder().name("Schneider-Lockman").build());
        models.add(Model.builder().name("Huels, Bauch and Lang").build());
        models.add(Model.builder().name("Douglas-Howell").build());
        models.add(Model.builder().name("McClure, Funk and Rogahn").build());
        models.add(Model.builder().name("Ratke-Schamberger").build());
        models.add(Model.builder().name("Kerluke-Brekke").build());
        makes.get(0).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Kiehn-Wintheiser").build());
        models.add(Model.builder().name("Klein Inc").build());
        models.add(Model.builder().name("Ritchie, Wisozk and Franecki").build());
        models.add(Model.builder().name("Hamill, Homenick and Upton").build());
        models.add(Model.builder().name("Hand and Sons").build());
        models.add(Model.builder().name("Feest and Sons").build());
        models.add(Model.builder().name("Jakubowski, Wuckert and Bins").build());
        models.add(Model.builder().name("Schinner-Wintheiser").build());
        models.add(Model.builder().name("Shanahan, Kihn and Donnelly").build());
        models.add(Model.builder().name("Ledner, O'Kon and Hirthe").build());
        models.add(Model.builder().name("Cormier, Breitenberg and Abshire").build());
        makes.get(1).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Hauck Inc").build());
        models.add(Model.builder().name("Satterfield-O'Conner").build());
        models.add(Model.builder().name("Schiller-Dickinson").build());
        models.add(Model.builder().name("Runte-Gutkowski").build());
        models.add(Model.builder().name("Dickens Inc").build());
        models.add(Model.builder().name("Kerluke Group").build());
        models.add(Model.builder().name("Lindgren-Graham").build());
        models.add(Model.builder().name("Berge LLC").build());
        models.add(Model.builder().name("Maggio and Sons").build());
        models.add(Model.builder().name("Thompson-Wolff").build());
        models.add(Model.builder().name("Bosco, Romaguera and Heathcote").build());
        makes.get(2).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Klocko, Krajcik and Krajcik").build());
        models.add(Model.builder().name("Abshire, Nikolaus and Zieme").build());
        models.add(Model.builder().name("Mueller, Jaskolski and Hamill").build());
        models.add(Model.builder().name("Larkin Group").build());
        models.add(Model.builder().name("Halvorson and Sons").build());
        models.add(Model.builder().name("Nolan, Pollich and Stamm").build());
        models.add(Model.builder().name("Kiehn Group").build());
        models.add(Model.builder().name("Howe-Bartoletti").build());
        models.add(Model.builder().name("Wintheiser-Sporer").build());
        models.add(Model.builder().name("Bergstrom Group").build());
        models.add(Model.builder().name("Batz LLC").build());
        makes.get(3).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Hane-Jenkins").build());
        models.add(Model.builder().name("Hamill Group").build());
        models.add(Model.builder().name("O'Reilly, Bergstrom and Reilly").build());
        models.add(Model.builder().name("Kovacek-Gaylord").build());
        models.add(Model.builder().name("Cronin Inc").build());
        models.add(Model.builder().name("Nolan, VonRueden and Lebsack").build());
        models.add(Model.builder().name("Stroman-Abernathy").build());
        models.add(Model.builder().name("Hartmann-Bechtelar").build());
        models.add(Model.builder().name("Medhurst LLC").build());
        models.add(Model.builder().name("Daniel-Purdy").build());
        models.add(Model.builder().name("Heller and Sons").build());
        makes.get(4).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Ruecker, Christiansen and Schuppe").build());
        models.add(Model.builder().name("Howell-Hackett").build());
        models.add(Model.builder().name("Mills, Klocko and Pollich").build());
        models.add(Model.builder().name("Homenick, Klocko and Robel").build());
        models.add(Model.builder().name("Zulauf, Hudson and Marvin").build());
        models.add(Model.builder().name("Wiegand Inc").build());
        models.add(Model.builder().name("Kautzer-Wintheiser").build());
        models.add(Model.builder().name("Hahn-Cronin").build());
        models.add(Model.builder().name("Harvey and Sons").build());
        models.add(Model.builder().name("Roberts-Conn").build());
        models.add(Model.builder().name("Murphy, Armstrong and Wehner").build());
        makes.get(5).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Bins-Rutherford").build());
        models.add(Model.builder().name("Moen, Cole and Vandervort").build());
        models.add(Model.builder().name("Ryan, Stiedemann and Metz").build());
        models.add(Model.builder().name("O'Connell and Sons").build());
        models.add(Model.builder().name("Kris-Beahan").build());
        models.add(Model.builder().name("Lang Inc").build());
        models.add(Model.builder().name("Mueller Group").build());
        models.add(Model.builder().name("Veum-Crist").build());
        models.add(Model.builder().name("Tromp, Heidenreich and Yost").build());
        models.add(Model.builder().name("Wintheiser Group").build());
        models.add(Model.builder().name("Kozey, Effertz and Wolf").build());
        makes.get(6).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Koepp Group").build());
        models.add(Model.builder().name("Blick, Bradtke and Dach").build());
        models.add(Model.builder().name("Strosin Inc").build());
        models.add(Model.builder().name("Klein, Harvey and Schultz").build());
        models.add(Model.builder().name("Jast, Zboncak and Bechtelar").build());
        models.add(Model.builder().name("Ratke, Mitchell and Monahan").build());
        models.add(Model.builder().name("Cruickshank, Brekke and King").build());
        models.add(Model.builder().name("Schowalter, Cremin and Smitham").build());
        models.add(Model.builder().name("Flatley Inc").build());
        models.add(Model.builder().name("Robel-Ernser").build());
        models.add(Model.builder().name("Koss, Schaefer and Schiller").build());
        makes.get(7).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Satterfield Group").build());
        models.add(Model.builder().name("Hermiston LLC").build());
        models.add(Model.builder().name("Harber, Bradtke and Price").build());
        models.add(Model.builder().name("Kemmer, Auer and Hegmann").build());
        models.add(Model.builder().name("Deckow-Renner").build());
        models.add(Model.builder().name("Swaniawski and Sons").build());
        models.add(Model.builder().name("Wisozk Inc").build());
        models.add(Model.builder().name("Boyer-Corwin").build());
        models.add(Model.builder().name("Williamson, Gutmann and Deckow").build());
        models.add(Model.builder().name("Greenfelder-Medhurst").build());
        models.add(Model.builder().name("Bradtke, Okuneva and Greenholt").build());
        makes.get(8).setModels(models);
        models = new LinkedList<>();
        makes.add(Make.builder().name("Bergstrom LLC").build());
        models.add(Model.builder().name("Mann LLC").build());
        models.add(Model.builder().name("O'Connell, Fahey and Botsford").build());
        models.add(Model.builder().name("Mayert-Crist").build());
        models.add(Model.builder().name("Corwin Inc").build());
        models.add(Model.builder().name("Fritsch and Sons").build());
        models.add(Model.builder().name("Morar Inc").build());
        models.add(Model.builder().name("Hammes, Pollich and Marvin").build());
        models.add(Model.builder().name("Schmeler, Swaniawski and Hane").build());
        models.add(Model.builder().name("Collins, Roob and Jacobson").build());
        models.add(Model.builder().name("Braun-Towne").build());
        makes.get(9).setModels(models);
        makeRepo.saveAll(makes);
        List<Listing> listings = new LinkedList<>();
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("When you play a game of thrones you win or you die.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(492479).year(1743).mileage(554366).type(Type.NEW).city(cities.get(4)).make(makes.get(0)).model(makes.get(0).getModels().get(4)).thumbnail("And I have a tender spot in my heart for cripples and bastards and broken things.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(4661).year(1832).mileage(442880).type(Type.NEW).city(cities.get(2)).make(makes.get(1)).model(makes.get(1).getModels().get(8)).thumbnail("Hodor? Hodor.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Once you’ve accepted your flaws, no one can use them against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(146617).year(1940).mileage(131019).type(Type.NEW).city(cities.get(3)).make(makes.get(5)).model(makes.get(5).getModels().get(3)).thumbnail("When you play a game of thrones you win or you die.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(335472).year(1775).mileage(432569).type(Type.NEW).city(cities.get(4)).make(makes.get(8)).model(makes.get(8).getModels().get(5)).thumbnail("Summer will end soon enough, and childhood as well.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(129949).year(1700).mileage(804795).type(Type.NEW).city(cities.get(7)).make(makes.get(9)).model(makes.get(9).getModels().get(4)).thumbnail("Once you’ve accepted your flaws, no one can use them against you.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("There are no heroes...in life, the monsters win.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(128134).year(1906).mileage(839628).type(Type.NEW).city(cities.get(9)).make(makes.get(9)).model(makes.get(9).getModels().get(2)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(167331).year(1738).mileage(726768).type(Type.NEW).city(cities.get(5)).make(makes.get(1)).model(makes.get(1).getModels().get(7)).thumbnail("All dwarfs are bastards in their father's eyes").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(354356).year(1991).mileage(379871).type(Type.NEW).city(cities.get(4)).make(makes.get(2)).model(makes.get(2).getModels().get(0)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Once you’ve accepted your flaws, no one can use them against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(121207).year(1728).mileage(499285).type(Type.NEW).city(cities.get(8)).make(makes.get(5)).model(makes.get(5).getModels().get(1)).thumbnail("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("When you play a game of thrones you win or you die.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(434815).year(1821).mileage(362667).type(Type.NEW).city(cities.get(6)).make(makes.get(0)).model(makes.get(0).getModels().get(8)).thumbnail("A lion doesn't concern itself with the opinion of sheep.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(0)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The things I do for love.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(317959).year(1985).mileage(986979).type(Type.VIP).city(cities.get(8)).make(makes.get(9)).model(makes.get(9).getModels().get(2)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Some old wounds never truly heal, and bleed again at the slightest word.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(308311).year(1721).mileage(78361).type(Type.VIP).city(cities.get(4)).make(makes.get(2)).model(makes.get(2).getModels().get(2)).thumbnail("Winter is coming.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(264158).year(1747).mileage(887303).type(Type.VIP).city(cities.get(1)).make(makes.get(9)).model(makes.get(9).getModels().get(2)).thumbnail("Nothing burns like the cold.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Fear cuts deeper than swords.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(167486).year(1839).mileage(107510).type(Type.VIP).city(cities.get(2)).make(makes.get(4)).model(makes.get(4).getModels().get(5)).thumbnail("Things are not always as they seemed, much that may seem evil can be good.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The North remembers.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(405209).year(1765).mileage(439018).type(Type.VIP).city(cities.get(3)).make(makes.get(2)).model(makes.get(2).getModels().get(1)).thumbnail("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Every flight begins with a fall.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(187088).year(1739).mileage(963976).type(Type.VIP).city(cities.get(0)).make(makes.get(8)).model(makes.get(8).getModels().get(4)).thumbnail("Fear cuts deeper than swords.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("When you play a game of thrones you win or you die.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(222363).year(1721).mileage(75732).type(Type.VIP).city(cities.get(5)).make(makes.get(3)).model(makes.get(3).getModels().get(9)).thumbnail("Every flight begins with a fall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("A lion doesn't concern itself with the opinion of sheep.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(368935).year(1720).mileage(596228).type(Type.VIP).city(cities.get(6)).make(makes.get(4)).model(makes.get(4).getModels().get(2)).thumbnail("Winter is coming.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The things I do for love.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(190919).year(1970).mileage(432375).type(Type.VIP).city(cities.get(5)).make(makes.get(9)).model(makes.get(9).getModels().get(5)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(484802).year(1715).mileage(873766).type(Type.VIP).city(cities.get(2)).make(makes.get(1)).model(makes.get(1).getModels().get(4)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(1)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(478865).year(1832).mileage(869453).type(Type.PAYED).city(cities.get(1)).make(makes.get(4)).model(makes.get(4).getModels().get(4)).thumbnail("There are no heroes...in life, the monsters win.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Fear cuts deeper than swords.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(327082).year(1723).mileage(228964).type(Type.PAYED).city(cities.get(1)).make(makes.get(9)).model(makes.get(9).getModels().get(4)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Every flight begins with a fall.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(75065).year(1763).mileage(803622).type(Type.PAYED).city(cities.get(6)).make(makes.get(4)).model(makes.get(4).getModels().get(2)).thumbnail("Winter is coming.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Do the dead frighten you?").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(272122).year(1917).mileage(822534).type(Type.PAYED).city(cities.get(0)).make(makes.get(1)).model(makes.get(1).getModels().get(4)).thumbnail("Do the dead frighten you?").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Laughter is poison to fear.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(125533).year(1753).mileage(581385).type(Type.PAYED).city(cities.get(0)).make(makes.get(1)).model(makes.get(1).getModels().get(9)).thumbnail("Every flight begins with a fall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Once you’ve accepted your flaws, no one can use them against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(332161).year(1712).mileage(8350).type(Type.PAYED).city(cities.get(6)).make(makes.get(8)).model(makes.get(8).getModels().get(1)).thumbnail("Give me honorable enemies rather than ambitious ones, and I'll sleep more easily by night.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(152881).year(1798).mileage(655228).type(Type.PAYED).city(cities.get(1)).make(makes.get(3)).model(makes.get(3).getModels().get(6)).thumbnail("Do the dead frighten you?").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Do the dead frighten you?").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(232878).year(1751).mileage(737432).type(Type.PAYED).city(cities.get(4)).make(makes.get(1)).model(makes.get(1).getModels().get(5)).thumbnail("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("There are no heroes...in life, the monsters win.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(382262).year(1989).mileage(819819).type(Type.PAYED).city(cities.get(6)).make(makes.get(5)).model(makes.get(5).getModels().get(1)).thumbnail("A lion doesn't concern itself with the opinion of sheep.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Knowledge could be more valuable than gold, more deadly than a dagger.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(27408).year(1936).mileage(236342).type(Type.PAYED).city(cities.get(0)).make(makes.get(1)).model(makes.get(1).getModels().get(3)).thumbnail("The North remembers.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(2)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("When you play a game of thrones you win or you die.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(167148).year(1955).mileage(862570).type(Type.PAYED).city(cities.get(7)).make(makes.get(5)).model(makes.get(5).getModels().get(7)).thumbnail("Nothing burns like the cold.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(331776).year(1793).mileage(803299).type(Type.PAYED).city(cities.get(7)).make(makes.get(0)).model(makes.get(0).getModels().get(8)).thumbnail("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Give me honorable enemies rather than ambitious ones, and I'll sleep more easily by night.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(112878).year(1837).mileage(827104).type(Type.PAYED).city(cities.get(2)).make(makes.get(4)).model(makes.get(4).getModels().get(4)).thumbnail("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Every flight begins with a fall.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(366821).year(1946).mileage(59241).type(Type.PAYED).city(cities.get(8)).make(makes.get(2)).model(makes.get(2).getModels().get(4)).thumbnail("When you play a game of thrones you win or you die.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(435712).year(1829).mileage(189193).type(Type.PAYED).city(cities.get(7)).make(makes.get(0)).model(makes.get(0).getModels().get(5)).thumbnail("The things I do for love.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Knowledge could be more valuable than gold, more deadly than a dagger.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(33338).year(1784).mileage(513545).type(Type.PAYED).city(cities.get(3)).make(makes.get(6)).model(makes.get(6).getModels().get(6)).thumbnail("When you play a game of thrones you win or you die.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(15343).year(1962).mileage(235871).type(Type.PAYED).city(cities.get(8)).make(makes.get(5)).model(makes.get(5).getModels().get(6)).thumbnail("All dwarfs are bastards in their father's eyes").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("There are no heroes...in life, the monsters win.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(498358).year(2014).mileage(595823).type(Type.PAYED).city(cities.get(5)).make(makes.get(4)).model(makes.get(4).getModels().get(5)).thumbnail("The North remembers.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Once you’ve accepted your flaws, no one can use them against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(448829).year(1841).mileage(871581).type(Type.PAYED).city(cities.get(5)).make(makes.get(3)).model(makes.get(3).getModels().get(9)).thumbnail("Give me honorable enemies rather than ambitious ones, and I'll sleep more easily by night.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(422416).year(1816).mileage(799367).type(Type.PAYED).city(cities.get(0)).make(makes.get(9)).model(makes.get(9).getModels().get(9)).thumbnail("Once you’ve accepted your flaws, no one can use them against you.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(3)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Fear cuts deeper than swords.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(140511).year(1969).mileage(416168).type(Type.PAYED).city(cities.get(5)).make(makes.get(5)).model(makes.get(5).getModels().get(3)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Some old wounds never truly heal, and bleed again at the slightest word.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(223750).year(1840).mileage(997816).type(Type.PAYED).city(cities.get(9)).make(makes.get(3)).model(makes.get(3).getModels().get(9)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Nothing burns like the cold.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(173934).year(1762).mileage(606739).type(Type.PAYED).city(cities.get(2)).make(makes.get(6)).model(makes.get(6).getModels().get(6)).thumbnail("A lion doesn't concern itself with the opinion of sheep.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(388578).year(1984).mileage(614067).type(Type.PAYED).city(cities.get(8)).make(makes.get(1)).model(makes.get(1).getModels().get(5)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(251933).year(1804).mileage(444421).type(Type.PAYED).city(cities.get(0)).make(makes.get(6)).model(makes.get(6).getModels().get(6)).thumbnail("Summer will end soon enough, and childhood as well.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(490913).year(1912).mileage(206191).type(Type.PAYED).city(cities.get(2)).make(makes.get(9)).model(makes.get(9).getModels().get(6)).thumbnail("Laughter is poison to fear.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Fear cuts deeper than swords.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(389493).year(1981).mileage(396739).type(Type.PAYED).city(cities.get(4)).make(makes.get(2)).model(makes.get(2).getModels().get(4)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Laughter is poison to fear.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(139864).year(1805).mileage(535165).type(Type.PAYED).city(cities.get(2)).make(makes.get(3)).model(makes.get(3).getModels().get(0)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Laughter is poison to fear.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(456483).year(1820).mileage(616653).type(Type.PAYED).city(cities.get(3)).make(makes.get(5)).model(makes.get(5).getModels().get(8)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The North remembers.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(128571).year(1811).mileage(780155).type(Type.PAYED).city(cities.get(1)).make(makes.get(2)).model(makes.get(2).getModels().get(6)).thumbnail("Once you’ve accepted your flaws, no one can use them against you.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(4)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("All dwarfs are bastards in their father's eyes").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(267698).year(2004).mileage(706670).type(Type.PAYED).city(cities.get(2)).make(makes.get(7)).model(makes.get(7).getModels().get(2)).thumbnail("And I have a tender spot in my heart for cripples and bastards and broken things.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(135396).year(1828).mileage(833071).type(Type.PAYED).city(cities.get(7)).make(makes.get(8)).model(makes.get(8).getModels().get(9)).thumbnail("Winter is coming.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("There are no heroes...in life, the monsters win.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(432547).year(1983).mileage(779037).type(Type.PAYED).city(cities.get(0)).make(makes.get(6)).model(makes.get(6).getModels().get(0)).thumbnail("Summer will end soon enough, and childhood as well.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(167126).year(1870).mileage(28026).type(Type.PAYED).city(cities.get(7)).make(makes.get(6)).model(makes.get(6).getModels().get(4)).thumbnail("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("A lion doesn't concern itself with the opinion of sheep.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(42845).year(1825).mileage(86273).type(Type.PAYED).city(cities.get(5)).make(makes.get(6)).model(makes.get(6).getModels().get(0)).thumbnail("Fear cuts deeper than swords.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(87396).year(1722).mileage(548909).type(Type.PAYED).city(cities.get(5)).make(makes.get(5)).model(makes.get(5).getModels().get(2)).thumbnail("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Things are not always as they seemed, much that may seem evil can be good.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(381899).year(1970).mileage(773790).type(Type.PAYED).city(cities.get(1)).make(makes.get(9)).model(makes.get(9).getModels().get(1)).thumbnail("Do the dead frighten you?").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Do the dead frighten you?").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(245305).year(1982).mileage(674180).type(Type.PAYED).city(cities.get(7)).make(makes.get(7)).model(makes.get(7).getModels().get(0)).thumbnail("Summer will end soon enough, and childhood as well.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("There are no heroes...in life, the monsters win.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(104488).year(1861).mileage(293394).type(Type.PAYED).city(cities.get(0)).make(makes.get(1)).model(makes.get(1).getModels().get(3)).thumbnail("When the snows fall and the white winds blow, the lone wolf dies but the pack survives.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(26046).year(1858).mileage(924982).type(Type.PAYED).city(cities.get(1)).make(makes.get(2)).model(makes.get(2).getModels().get(5)).thumbnail("Do the dead frighten you?").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(5)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(12353).year(1873).mileage(18242).type(Type.PAYED).city(cities.get(5)).make(makes.get(8)).model(makes.get(8).getModels().get(5)).thumbnail("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Once you’ve accepted your flaws, no one can use them against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(190107).year(2003).mileage(958319).type(Type.PAYED).city(cities.get(3)).make(makes.get(5)).model(makes.get(5).getModels().get(4)).thumbnail("Hodor? Hodor.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("When the snows fall and the white winds blow, the lone wolf dies but the pack survives.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(428512).year(1953).mileage(843103).type(Type.PAYED).city(cities.get(8)).make(makes.get(6)).model(makes.get(6).getModels().get(2)).thumbnail("Hodor? Hodor.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Do the dead frighten you?").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(271714).year(1724).mileage(984034).type(Type.PAYED).city(cities.get(3)).make(makes.get(5)).model(makes.get(5).getModels().get(7)).thumbnail("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Some old wounds never truly heal, and bleed again at the slightest word.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(222183).year(1983).mileage(589447).type(Type.PAYED).city(cities.get(2)).make(makes.get(8)).model(makes.get(8).getModels().get(8)).thumbnail("Laughter is poison to fear.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("When the snows fall and the white winds blow, the lone wolf dies but the pack survives.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(153302).year(1814).mileage(342854).type(Type.PAYED).city(cities.get(4)).make(makes.get(4)).model(makes.get(4).getModels().get(6)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(78185).year(1863).mileage(516242).type(Type.PAYED).city(cities.get(7)).make(makes.get(0)).model(makes.get(0).getModels().get(0)).thumbnail("Fear cuts deeper than swords.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(492524).year(1853).mileage(220131).type(Type.PAYED).city(cities.get(2)).make(makes.get(0)).model(makes.get(0).getModels().get(2)).thumbnail("When you play a game of thrones you win or you die.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(243641).year(1959).mileage(229235).type(Type.PAYED).city(cities.get(5)).make(makes.get(3)).model(makes.get(3).getModels().get(1)).thumbnail("The North remembers.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("And I have a tender spot in my heart for cripples and bastards and broken things.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(154421).year(1810).mileage(796240).type(Type.PAYED).city(cities.get(9)).make(makes.get(3)).model(makes.get(3).getModels().get(5)).thumbnail("When the snows fall and the white winds blow, the lone wolf dies but the pack survives.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(6)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Things are not always as they seemed, much that may seem evil can be good.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(398053).year(1947).mileage(419840).type(Type.PAYED).city(cities.get(5)).make(makes.get(0)).model(makes.get(0).getModels().get(7)).thumbnail("Things are not always as they seemed, much that may seem evil can be good.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Hodor? Hodor.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(35489).year(1844).mileage(731461).type(Type.PAYED).city(cities.get(8)).make(makes.get(9)).model(makes.get(9).getModels().get(8)).thumbnail("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(365899).year(1918).mileage(120919).type(Type.PAYED).city(cities.get(4)).make(makes.get(3)).model(makes.get(3).getModels().get(4)).thumbnail("Things are not always as they seemed, much that may seem evil can be good.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(358312).year(1775).mileage(298064).type(Type.PAYED).city(cities.get(5)).make(makes.get(8)).model(makes.get(8).getModels().get(3)).thumbnail("Hodor? Hodor.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Fear cuts deeper than swords.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(266670).year(1767).mileage(157157).type(Type.PAYED).city(cities.get(4)).make(makes.get(1)).model(makes.get(1).getModels().get(1)).thumbnail("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The North remembers.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(176846).year(1759).mileage(996782).type(Type.PAYED).city(cities.get(6)).make(makes.get(9)).model(makes.get(9).getModels().get(9)).thumbnail("Laughter is poison to fear.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("All dwarfs are bastards in their father's eyes").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(185964).year(1715).mileage(693709).type(Type.PAYED).city(cities.get(7)).make(makes.get(5)).model(makes.get(5).getModels().get(6)).thumbnail("Winter is coming.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(136778).year(1802).mileage(238656).type(Type.PAYED).city(cities.get(8)).make(makes.get(9)).model(makes.get(9).getModels().get(1)).thumbnail("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(220055).year(1845).mileage(60330).type(Type.PAYED).city(cities.get(8)).make(makes.get(4)).model(makes.get(4).getModels().get(4)).thumbnail("Do the dead frighten you?").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Every flight begins with a fall.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(244364).year(1752).mileage(826079).type(Type.PAYED).city(cities.get(4)).make(makes.get(8)).model(makes.get(8).getModels().get(1)).thumbnail("Fear cuts deeper than swords.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(7)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("All dwarfs are bastards in their father's eyes").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(410759).year(1923).mileage(469882).type(Type.PAYED).city(cities.get(1)).make(makes.get(7)).model(makes.get(7).getModels().get(5)).thumbnail("There are no heroes...in life, the monsters win.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("There are no heroes...in life, the monsters win.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(255234).year(1731).mileage(390165).type(Type.PAYED).city(cities.get(5)).make(makes.get(5)).model(makes.get(5).getModels().get(5)).thumbnail("The things I do for love.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The North remembers.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(432080).year(2016).mileage(347936).type(Type.PAYED).city(cities.get(5)).make(makes.get(3)).model(makes.get(3).getModels().get(4)).thumbnail("Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("A lion doesn't concern itself with the opinion of sheep.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(194783).year(1760).mileage(43122).type(Type.PAYED).city(cities.get(8)).make(makes.get(7)).model(makes.get(7).getModels().get(0)).thumbnail("When you play a game of thrones you win or you die.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Give me honorable enemies rather than ambitious ones, and I'll sleep more easily by night.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(116861).year(1850).mileage(809229).type(Type.PAYED).city(cities.get(1)).make(makes.get(4)).model(makes.get(4).getModels().get(8)).thumbnail("Nothing burns like the cold.").updateTime(LocalDateTime.now()).build()).color(Color.values()[0]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(281952).year(1803).mileage(813055).type(Type.PAYED).city(cities.get(8)).make(makes.get(4)).model(makes.get(4).getModels().get(8)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[0]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The things I do for love.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(300544).year(1802).mileage(722308).type(Type.PAYED).city(cities.get(3)).make(makes.get(9)).model(makes.get(9).getModels().get(8)).thumbnail("The North remembers.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[1]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("A lion doesn't concern itself with the opinion of sheep.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(235475).year(1702).mileage(766682).type(Type.PAYED).city(cities.get(0)).make(makes.get(6)).model(makes.get(6).getModels().get(0)).thumbnail("Knowledge could be more valuable than gold, more deadly than a dagger.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(34316).year(1876).mileage(206463).type(Type.PAYED).city(cities.get(1)).make(makes.get(5)).model(makes.get(5).getModels().get(0)).thumbnail("Every flight begins with a fall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("The things I do for love.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(125340).year(1914).mileage(581607).type(Type.PAYED).city(cities.get(4)).make(makes.get(7)).model(makes.get(7).getModels().get(6)).thumbnail("The things I do for love.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(8)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(430345).year(1785).mileage(206905).type(Type.PAYED).city(cities.get(7)).make(makes.get(7)).model(makes.get(7).getModels().get(2)).thumbnail("Hodor? Hodor.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(0)).creditOption(intToBoolean(1)).price(6718).year(1732).mileage(615463).type(Type.PAYED).city(cities.get(4)).make(makes.get(3)).model(makes.get(3).getModels().get(2)).thumbnail("The North remembers.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[1]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(1)).price(83820).year(1864).mileage(795922).type(Type.PAYED).city(cities.get(4)).make(makes.get(9)).model(makes.get(9).getModels().get(0)).thumbnail("Nothing burns like the cold.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[1]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Every flight begins with a fall.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(331163).year(1897).mileage(206319).type(Type.PAYED).city(cities.get(3)).make(makes.get(9)).model(makes.get(9).getModels().get(1)).thumbnail("Winter is coming.").updateTime(LocalDateTime.now()).build()).color(Color.values()[1]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(54824).year(1832).mileage(286674).type(Type.PAYED).city(cities.get(0)).make(makes.get(9)).model(makes.get(9).getModels().get(3)).thumbnail("And I have a tender spot in my heart for cripples and bastards and broken things.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[0]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(117985).year(1866).mileage(502656).type(Type.PAYED).city(cities.get(5)).make(makes.get(9)).model(makes.get(9).getModels().get(6)).thumbnail("And so he spoke, and so he spoke, that Lord of Castamere, but now the rains weep o'er his hall, with no one there to hear. Yes, now the rains weep o'er his hall, and not a soul to hear.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Winter is coming.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(288909).year(1817).mileage(117203).type(Type.PAYED).city(cities.get(2)).make(makes.get(7)).model(makes.get(7).getModels().get(6)).thumbnail("Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[0]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("... a mind needs books as a sword needs a whetstone, if it is to keep its edge.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(458123).year(1905).mileage(862390).type(Type.PAYED).city(cities.get(8)).make(makes.get(9)).model(makes.get(9).getModels().get(0)).thumbnail("Some old wounds never truly heal, and bleed again at the slightest word.").updateTime(LocalDateTime.now()).build()).color(Color.values()[4]).fuelType(FuelType.values()[2]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").baseListing(BaseListing.builder().barterOption(intToBoolean(1)).leaseOption(intToBoolean(0)).cashOption(intToBoolean(0)).creditOption(intToBoolean(0)).price(419603).year(1848).mileage(970886).type(Type.PAYED).city(cities.get(6)).make(makes.get(1)).model(makes.get(1).getModels().get(8)).thumbnail("Never forget who you are. The rest of the world won't. Wear it like an armor and it can never be used against you.").updateTime(LocalDateTime.now()).build()).color(Color.values()[2]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[1]).gearBox(GearBox.values()[2]).user(users.get(9)).build());
        listings.add(Listing.builder().autoPay(true).creationDate(LocalDateTime.now()).endDate(LocalDate.now().plusMonths(1)).description("And I have a tender spot in my heart for cripples and bastards and broken things.").baseListing(BaseListing.builder().barterOption(intToBoolean(0)).leaseOption(intToBoolean(1)).cashOption(intToBoolean(1)).creditOption(intToBoolean(0)).price(310568).year(1971).mileage(451623).type(Type.PAYED).city(cities.get(8)).make(makes.get(3)).model(makes.get(3).getModels().get(9)).thumbnail("Every flight begins with a fall.").updateTime(LocalDateTime.now()).build()).color(Color.values()[3]).fuelType(FuelType.values()[3]).bodyType(BodyType.values()[0]).gearBox(GearBox.values()[2]).user(users.get(9)).build());
//        for (int i = 0; i < 10; i++) {
//            for (int j = 0; j < 10; j++) {
//                int n = random.nextInt(10);
//                System.out.println("listings.add(Listing.builder()" +
//                        ".autoPay(true)" +
//                        ".creationDate(LocalDateTime.now())" +
//                        ".endDate(LocalDate.now().plusMonths(1))" +
//                        ".description(\"%s\")" .formatted(faker.gameOfThrones().quote()) +
//                        ".baseListing(BaseListing.builder()" +
//                        ".barterOption(intToBoolean(%d))" .formatted(random.nextInt(2)) +
//                        ".leaseOption(intToBoolean(%d))" .formatted(random.nextInt(2)) +
//                        ".cashOption(intToBoolean(%d))" .formatted(random.nextInt(2)) +
//                        ".creditOption(intToBoolean(%d))" .formatted(random.nextInt(2)) +
//                        ".price(%d)" .formatted(random.nextInt(500000)) +
//                        ".year(%d)" .formatted(random.nextInt(322) + 1700) +
//                        ".mileage(%d)" .formatted(random.nextInt(1_000_000)) +
//                        ".type(%s)" .formatted(i > 1 ? "Type.PAYED" : i == 0 ? "Type.NEW" : "Type.VIP") +
//                        ".city(cities.get(%d))" .formatted(random.nextInt(10)) +
//                        ".make(makes.get(%d))" .formatted(n) +
//                        ".model(makes.get(%d).getModels().get(%d))" .formatted(n, random.nextInt(10)) +
//                        ".thumbnail(\"%s\")" .formatted(faker.gameOfThrones().quote()) +
//                        ".updateTime(LocalDateTime.now()).build())" +
//                        ".color(Color.values()[%d])" .formatted(random.nextInt(5)) +
//                        ".fuelType(FuelType.values()[%d])" .formatted(random.nextInt(4)) +
//                        ".bodyType(BodyType.values()[%d])" .formatted(random.nextInt(2)) +
//                        ".gearBox(GearBox.values()[%d])" .formatted(random.nextInt(3)) +
//                        ".user(users.get(%d)).build());" .formatted(i));
//            }
//        }
        listRepo.saveAll(listings);
    }

    private Boolean intToBoolean(int n) {
        return n != 0;
    }
}